services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    # volumes:
    #   - ./pgdata-dev:/var/lib/postgresql/data 