version: "3.8"

services:
  # server:
  #   container_name: server
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   command: npm start
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - '${SERVER_PORT}:${SERVER_PORT}'
  #   depends_on:
  #     - db

  # client:
  #   container_name: client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   command: node server.js
  #   env_file:
  #     - .env
  #   restart: always
  #   ports:
  #     - '${CLIENT_PORT}:${CLIENT_PORT}'
  #   depends_on:
  #     - db

  db:
    container_name: db
    image: postgres:13
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    # volumes:
    #   - './db-data:/data/db'