import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import ReduxProvider from '../redux/features/provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Болото",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <link rel="icon" href="/logo.jpeg" sizes="any" />
      <html lang="en">
        <body className={inter.className}>
          <ReduxProvider>{children}</ReduxProvider>
        </body>
      </html>
    </>
  );
}
